# -*- coding: utf-8 -*-
"""Copy of modül3_hafta3_gorsellestirme_homework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ch7z0MWdhp3gwg3i-VzQEK4-fzwtUBPD

# 🎓 Titanic Veri Seti Görselleştirme Uygulamaları
Her sorunun altında cevabınızı kodlayabilirsiniz.
Grafiklerinizi yorumlamanız ve grafikten çıkarımlarınızı yazmanız gerekmektedir.

## 🟢 Kolay Seviye

### ❓ Soru: Cinsiyete göre yolcu sayısını görselleştirin. (örn. countplot veya bar chart)
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = sns.load_dataset("titanic")

df.head()

survived_counts = df['sex'].value_counts()

plt.figure(figsize=(6,4))
plt.bar(survived_counts.index, survived_counts.values, color=['pink', 'pink'])
plt.xlabel('Sex')
plt.ylabel('Count')
plt.grid(axis='y', linestyle= '--', alpha= 0.7)
plt.title('Count of passenger by sex')
plt.tight_layout()
plt.show()

"""### ❓ Soru: "Survived" değişkeninin dağılımını çiziniz."""

# Cevabınızı buraya yazınız
plt.figure(figsize=(8,5))
plt.bar(survived_counts.index, survived_counts.values, color = 'pink')
plt.title('Survived Distrubution')
plt.xticks([0,1], ['No', 'Yes'])
plt.xlabel('Survived')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle= '--', alpha= 0.7)
plt.show()

"""### ❓ Soru: "Pclass" değişkeninin histogramını veya çubuk grafiğini oluşturun."""

# Cevabınızı buraya yazınız
plt.figure(figsize=(8,5))
plt.hist(df['class'],bins=10, color="pink", edgecolor='black')
plt.title('Pclass Distribution')
plt.xlabel('Pclass')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle= '--', alpha= 0.7)
plt.tight_layout()
plt.show()

"""### ❓ Soru: "Age" değişkeninin histogramını çiziniz."""

plt.figure(figsize=(8,5))
plt.hist(df["age"], bins=20, color="pink", edgecolor='black')
plt.title("Yaş Dağılımı")
plt.xlabel("Yaş")
plt.ylabel("Frekans")
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""### ❓ Soru: "Fare" değişkeninin histogramını çizip açıklayınız."""

# Cevabınızı buraya yazınız
plt.figure(figsize=(8,5))
plt.hist(df["fare"], bins=20, color="pink", edgecolor='black')
plt.title("Fare Dağılımı")
plt.xlabel("Fare")
plt.ylabel("")

"""**Ağır sağ kuyruklu dağılım (right skewed)**: Verinin çoğu çok düşük değerlerde yoğunlaşmış (0-50 arası). Daha büyük değerler daha seyrek ve daha sağ tarafa doğru uzun bir kuyruk oluşturuyor. **Pozitif çarpıklık** olan bir dağılım.

**Moda (En sık değer)**: En yüksek çubuğun bulunduğu x değeri, bu değişkenin modasıdır(yani en çok tekrar eden değer aralığı).
(0-20) arası.

**Aykırı Değerler**: 500 civarında da örnek var. Bu değerler, veri setinde aykırı (outlier) olarak kabul edilebilir.

 "'Fare' değişkeni büyük oranda düşük değerlere sahiptir. 0–50 aralığına düşen değerler oldukça yaygınken, daha yüksek değerler nadiren gözlenmiştir. Dağılım, sağa çarpık olup, pozitif yönde bir kuyruk oluşturmaktadır."

## 🟡 Orta Seviye

### ❓ Soru: Cinsiyete göre yaş dağılımını karşılaştırın. (örn. boxplot, violinplot, kdeplot)
"""

# Cevabınızı buraya yazınız
sns.kdeplot(data=df, x='age', hue='sex', fill=True)
plt.title('Age Distribution by Sex (KDE)')
plt.xlabel('Age')
plt.ylabel('Density')
plt.show()

"""### ❓ Soru: Pclass'a göre ücret dağılımını inceleyin."""

# Cevabınızı buraya yazınız
sns.boxplot(data=df, x='class', y='fare', color='pink')
plt.title('Fare Distribution by Class')
plt.xlabel('Class')
plt.ylabel('Fare')
plt.show()

"""### ❓ Soru: Survived’a göre yaş dağılımını inceleyin."""

import seaborn as sns
import matplotlib.pyplot as plt
g = sns.FacetGrid(df, col='survived', row='sex', margin_titles=True, height=3)
g.map(sns.histplot, 'age', color='pink')
plt.show()

"""### ❓ Soru: Cinsiyet ve sınıfa göre hayatta kalma oranlarını barplot ile karşılaştırın."""

# Cevabınızı buraya yazınız
plt.figure(figsize=(10,6))
sns.barplot(x="class", y="survived", hue="sex", data=df, palette="pastel")


plt.title("Cinsiyet ve Sınıfa Göre Hayatta Kalma Oranları")
plt.xlabel("Yolcu Sınıfı")
plt.ylabel("Hayatta Kalma Oranı")
plt.ylim(0, 1)  # oran olduğu için 0–1 arası
plt.legend(title="Cinsiyet")
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.show()

"""### ❓ Soru: FacetGrid ile cinsiyete göre yaş histogramlarını ayrı ayrı gösterin."""

# Cevabınızı buraya yazınız
g = sns.FacetGrid(df, col='sex', margin_titles=True, height=3)
g.map(sns.histplot, 'age', color='pink')
plt.show()

"""### ❓ Soru: "Fare" ve "Age" değişkenleri arasında scatterplot oluşturun."""

# Cevabınızı buraya yazınız
plt.figure(figsize=(8,6))
plt.scatter(df['age'], df['fare'], alpha = 0.6, c="magenta", edgecolors="k", linewidths=0.5)
plt.title("Yaş ve Ücret Scatterplot")
plt.xlabel("Yaş")
plt.ylabel("Ücret")
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.show()

"""### ❓ Soru: Korelasyon matrisi ve heatmap ile değişkenler arasındaki ilişkiyi görselleştirin."""

# Cevabınızı buraya yazınız
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot= True,cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

"""**+1:** mükemmel pozitif ilişki

**0:**hiçibir doğrusal ilişki yok

**-1:**mükemmmel negatif ilişki

Korelasyon Katsayısı (r)	           Yorum

---



+0.80  +1.00	           \    🔥 Çok güçlü pozitif ilişki

+0.60  +0.79	           \    💪 Güçlü pozitif ilişki

+0.40  +0.59	           \    👍 Orta düzeyde pozitif ilişki

+0.20  +0.39	           \    🙂 Zayıf pozitif ilişki

+0.00  +0.19	           \    ⚪ Çok zayıf/önemsiz pozitif ilişki

0	                       \    🚫 Hiç ilişki yok

–0.00  –0.19	           \    ⚪ Çok zayıf/önemsiz negatif ilişki

–0.20  –0.39	           \    🙂 Zayıf negatif ilişki

–0.40  –0.59	           \    👍 Orta düzeyde negatif ilişki

–0.60  –0.79	           \    💪 Güçlü negatif ilişki

–0.80  –1.00	           \    🔥 Çok güçlü negatif ilişki


# **negatif korelasyon demek = ters orantı demektir**

## 🔴 İleri Seviye

### ❓ Soru: "Age" değişkeninin çarpıklık (skewness) ve basıklığını (kurtosis) hesaplayın ve yorumlayın.
"""

# Cevabınızı buraya yazınız
age_data = df['age'].dropna()
age_skewness = age_data.skew() # çarpıklık
age_kurtosis = age_data.kurtosis() # basıklılık

print(f"Yaş değişkeninin çarpıklığı: {age_skewness}")
print(f"Yaş değişkeninin basıklılığı: {age_kurtosis}")

sns.histplot(age_data, kde=True)
plt.title("Yaş Dağılımı")
plt.xlabel("Yaş")
plt.ylabel("Frekans")

"""Yaşların büyük bir kısmının genç bireylerde toplanmış. (20-30)

Sağ tarfta kuyruk - veri sağa çarpık

Az sayıda da olsa yaşlı bireyler var (70+) bu dağılım sağa doğru

# **çarpıklık (Skewness): 0.389**

pozitif çarpıklık sağa çarpıklık var ama değeri 0.5'ten küçük, yani hafif çarpıklık söz konusu. Bu demekki yaş arttıkça birey saısı azalıyor.

# **Basıklık (Kurtosis): 0.178**

0'a çok yakın yani normal dağılıma çok yakın, ne sivri be de basık bir dağılım var.

hafif pozitif değer olması, uç değerleri (özellikle yaşlı bireylerin) az da olsa sağılımda etkili olduğunu gösteriyr.

### ❓ Soru: Seaborn pairplot ile sayısal değişkenleri inceleyin. Hayatta kalma durumunu hue parametresiyle ayırın.
"""

# Cevabınızı buraya yazınız
# sadece sayısal sütunları al
numeric_df = df.select_dtypes(include='number')

sns.pairplot(numeric_df, hue='survived')
plt.show()

"""### ❓ Soru: "Sex", "Pclass" ve "Survived" değişkenlerini içeren gruplu bir violinplot oluşturun."""

# Cevabınızı buraya yazınız
sns.violinplot(data=df, x="class", y="survived", hue="sex")

"""### ❓ Soru: "Embarked" değişkenine göre fare dağılımını inceleyin."""

# Cevabınızı buraya yazınız
sns.boxplot(data=df, x="embarked", y="fare")
plt.show()

"""### ❓ Soru: Plotly ile cinsiyet ve sınıfa göre interaktif bir histogram oluşturun."""

# Cevabınızı buraya yazınız
import plotly.express as px
#fig = px.bar(x=df['sex'], y=df['class'], color=df['survived'])
#fig.show()
fig = px.histogram(df,
                   x="pclass",                # x ekseni: sınıf
                   color="sex",              # renk: cinsiyet
                   barmode="group",          # gruplandırılmış barlar
                   title="Cinsiyet ve Sınıfa Göre Yolcu Dağılımı",
                   labels={"pclass": "Yolcu Sınıfı", "count": "Kişi Sayısı"})

fig.update_layout(bargap=0.2)  # barlar arası boşluk
fig.show()

"""### ❓ Soru: Eksik veri analizi yaparak eksik verileri heatmap ile görselleştirin."""

# Cevabınızı buraya yazınız
missing_values = df.isnull()
missing_values
sns.heatmap(missing_values, cmap='viridis', cbar=False)
plt.show()

"""### ❓ Soru: Cinsiyet ve yaş arasındaki ilişkiyi scatterplot ile gösterip renkleri hayatta kalma durumuna göre ayarlayın."""

# Cevabınızı buraya yazınız
sns.scatterplot(data=df, x='sex', y='age', hue='survived')
plt.show()

"""### ❓ Soru: Matplotlib ile özelleştirilmiş bir bar grafiği oluşturun (renk, kalınlık, grid, label)."""

# Cevabınızı buraya yazınız
survived_by_class = df[df["survived"] == 1]["class"].value_counts().sort_index()

classes = ["1.sınıf", "2.sınıf", "3.sınıf"]

colors = ['mediumseagreen', 'gold', 'tomato']


plt.figure(figsize=(8, 6))
bars = plt.bar(classes, survived_by_class, color=colors, edgecolor='black', linewidth=2)

# Grid çizgileri
plt.grid(axis='y', linestyle='--', alpha=0.6)
# Eksen etiketleri ve başlık
plt.xlabel("Yolcu Sınıfı", fontsize=12)
plt.ylabel("Hayatta Kalan Sayısı", fontsize=12)
plt.title("Sınıfa Göre Hayatta Kalan Yolcular", fontsize=14)

# Sayıları çubukların üstüne yazdır
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 2, int(yval),
             ha='center', va='bottom', fontsize=10)
#plt.xlabel("Sınıf")
#plt.ylabel("Hayatta Kalma Sayısı")
#plt

"""## 📘 Bonus Yorumlama Soruları

### ❓ Soru: Korelasyonu yüksek olan iki değişken bulun. İlişkilerini grafikle açıklayın.

Isı haritasına bazı yüksek korelasyonlar:

sibsp ile parch: 0.41

adult_male ile survived: -0.56

pclass ile fare: -0.55

sibsp ile alone: -0.58

parch ile alone: -0.58




Isı haritasına göre en yüksek pozitif korelasyona sahip değişken çifti:

sibsp (kardeş/eş sayısı) ile parch (ebeveyn/çocuk sayısı)

Korelasyon katsayısı: 0.41
"""

# Cevabınızı buraya yazınız
plt.figure(figsize=(6, 4))
sns.scatterplot(df, x="sibsp", y="parch", alpha=0.6)
plt.title("Sibsp ile Parch Arasındaki İlişki")
plt.xlabel("Sibsp (Kardeş/Eş Sayısı)")
plt.ylabel("Parch (Ebeveyn/Çocuk Sayısı)")
plt.grid(True)
plt.show()

"""İki ya da daha çok değişken arasındaki ilişkinin matematiksel bağıntısı “**Regresyon Analiz**i” ile ilişkinin yönü ve derecesi ise “**Korelasyon Analizi**” ile incelenir.


Korelasyon katsayısı, bağımlı değişken ile bağımsız değişkenler arasındaki ilişkinin gücünü gösteren bir katsayıdır. Örneğin; öğrencinin ders çalışma süresi ile aldığı istatistik notu arasında ilişki olup olmadığını veya borsada işlem gören bir hisse senedinin belli bir dönemdeki günlük getirisi (X) ile içinde yer aldığı bir endeksin günlük getirisi (Y) arasındaki ilişki korelasyon katsayısı ile incelenebilir. Korelasyon katsayısı değişkenlerin yönü ve etkileşimlerin nasıl olduğu hakkında bilgi verir.

Korelasyon katsayısı, açıklanan varyans açıklanamayan varyans oranı olarak tanımlanır.

Korelasyon katsayısı iki değişken arasındaki doğrusal ilişkinin ölçüsü olup incelenen değişkenlerin birimlerinden bağımsızdır ve -1 ≤ r ≤1 arasındadır. Yani 5 ya da -5 olamaz. Korelasyon katsayısının 0’a yaklaşması değişkenler arasında zayıf ilişkinin varlığını gösterir. Değişkenler birlikte artıyor veya azalıyorsa pozitif yönde, değişkenlerden biri artarken diğeri azalıyorsa ise negatif yönde bir ilişki vardır.

### ❓ Soru: En fazla hayatta kalan grup hangisidir? (Cinsiyet + Sınıf)
"""

# Cevabınızı buraya yazınız
survived_counts = df.groupby(['sex', 'class'])['survived'].sum()
survived_counts

"""*91 hayatta kalan kişi sayısı ile first classtaki kadın yolcular*

### ❓ Soru: Yaş dağılımı normal mi? Neden?
"""

# Cevabınızı buraya yazınız
sns.histplot(df['age'], kde=True)
plt.title("Yaş Dağılımı")
plt.xlabel("Yaş")
plt.ylabel("Frekans")
plt.show()

"""*NORMAL DAĞILIM DEĞİL*

Histogram çubukları ve üzerine çizilen KDE eğrisi (yoğunluk eğrisi), yaşların nasıl dağıldığını gösteriyor.

En yüksek frekans 20–30 yaş aralığında.

Dağılım asimetrik (sağa çarpık).


**Normal dağılım (Gauss eğrisi) şu özelliklere sahip olur:**

Simetriktir (ortalama ≈ medyan ≈ mod).

En çok kişi ortalamaya yakın yaşlardadır, uçlarda az kişi vardır.

### ❓ Soru: Violinplot ile boxplot’ın farkı nedir?
"""

# Cevabınızı buraya yazınız

"""# **Boxplot (Kutu Grafiği):**
Amaç: Verinin temel istatistiksel dağılımını göstermek.

**Gösterdikleri:**

Minimum (uç değerler hariç)

çeyrek (Q1)

Medyan (ortanca)

çeyrek (Q3)

Maksimum (uç değerler hariç)

Uç değerler (nokta olarak)

# **Violinplot (Keman Grafiği):**
Boxplot + Yoğunluk eğrisi birleşimidir.

Amaç: Verinin dağılımını ve yoğunluğunu aynı anda göstermek.

İçinde genellikle bir boxplot bulunur, ayrıca etrafında veri yoğunluğunu gösteren simetrik bir KDE eğrisi vardır.


Verinin şekli ve simetrisi daha net anlaşılır.

Çift tepe (bimodal), sağa/sola çarpıklık gibi detayları gösterir.

### ❓ Soru: Grafiklerde dikkat edilmesi gereken 3 temel ipucu nedir?
"""

# Cevabınızı buraya yazınız

"""1) Doğru ve Açık Etiket

 2)Doğru Grafik seçimi

 3)Gereksiz görsel kalabalıktan kaçınma

## 🧠 Refleksiyon

**En çok şaşırdığınız veya dikkat çeken sonuç neydi? Görselleştirme size veriyle ilgili hangi içgörüleri sağladı?**
"""

# Yorumunuzu buraya yazınız

"""

Sınıf farklılıkları: Sadece konfor değil, güvenlik konusunda da ayrımcılık

Toplumsal normlar: 1912'deki cinsiyet rolleri ve sosyal beklentilerin etkisi

Hiyerarşik yapı: Sosyal statünün yaşam-ölüm kararlarındaki rolü



Kategorik değişkenlerin gücü: Cinsiyet ve sınıf gibi kategorik faktörlerin sayısal değişkenlerden daha belirleyici olması



Sosyal faktörleriin ölçülebilirliği: Toplumsal dinamiklerin istatistiksel verilerle kanıtlanabilmesi"""